services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio_consultas
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
